language: generic

sudo: required
services:
    - docker
before install:
    - docker build -t erickc80/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true erickc80/react-test npm test

after_success:
    - docker build -t erickc80/multi-client ./client
    - docker build -t erickc80/multi-nginx ./nginx
    - docker build -t erickc80/multi-server ./server
    - docker build -t erickc80/multi-worker ./worker

# Log in to the docker CLI 
    - echo "$docker_password" | docker login -u "$docker_id" --password-stdin  
# take those images and push to docker hub

    - docker push erickc80/multi-client
    - docker push erickc80/multi-nginx
    - docker push erickc80/multi-server
    - docker push erickc80/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: multidocker-env
    bucket_name: elasticbeanstalk-us-east-1-032015446853
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
        
